ansi library can now support color tags split across lines
starkandwayne/goutils pull request #5
Opened 2016-11-10 17:54 UTC by thomasmmitchell

Added the flag to make the `.` regexp operator match the newline character.

2016-11-11 14:48 UTC, jhunt commented
Can you add tests that both confirm the original bug and verify the proposed fix?

2016-11-11 14:49 UTC, jhunt requested changes
Can you add tests that both confirm the original bug and verify the proposed fix?

2016-11-12 01:28 UTC, thomasmmitchell commented
Don't like to put two separate things on one ticket, but just trying to avoid the PR overhead. Any issues?

2016-11-12 18:10 UTC, jhunt approved these changes

2016-11-12 18:10 UTC, merged

2016-11-12 18:10 UTC, jhunt commented
In the future, try to keep to one fix/feature per PR.